### ISSUE TITLE
Cannot craft items in auto ancient altar from fluffy

### ISSUE THREAD

**Issue by lucasGithuber** [Slimefun-Addon-Community/DynaTech#10]
## Description (Required)
cant make recipes in FluffyMachine's auto ancient altar
i tried putting the tesseracting object into it and it didnt craft it, but it worked with items from other addons
## Steps to reproduce the Issue (Required)
put the recipe in the auto ancient altar, power it, enable/click craft once button

## Expected behavior (Required)
the item to be crafted

## Server Log / Error Report
im not the server owner, but i dont think this should throw an error

## Environment (Required)

 - Minecraft Version: 1.18.1-R0.1-SNAPSHOT
 - CS-CoreLib Version: none
 - Slimefun Version: DEV 1006
 - Plugin Version: DEV 160

**Comment by J3fftw1** [comment]
Report this on the repo of fluffymachines not a dynatech issue
