### ISSUE TITLE
Liquid Tank

### ISSUE THREAD

**Issue by Sefiraat** [Slimefun-Addon-Community/DynaTech#2]
## Description (Required)

The liquid tank - doesn't calculate liquids going in correctly, being placed correctly, and water that is displaced doesn't flow back correctly. 

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by Boomer-1** [comment]
you guys figured this one out already?

**Comment by Sefiraat** [comment]
Kinda, we have the cause and the fix, it's linked to the other open issue around blocks not updating and will be in the fix for that. the issue is how to approach it as it's awkward
